/**
 * Preview server: serves a project (fixture or generated) through Vite with
 * the bridge shim injected. The project's own vite.config.ts is loaded, so
 * its plugins (react, tailwind) resolve from the project's node_modules;
 * the shim plugin is added from outside — the project files never reference
 * shim code (see docs/decisions.md).
 */

import { existsSync, mkdirSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import type { IncomingMessage, ServerResponse } from "node:http";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { Plugin, ViteDevServer } from "vite";
import { createServer, normalizePath } from "vite";
import { exportApiPlugin } from "./export-api.ts";
import { MAX_BODY_BYTES } from "./max-body-bytes.ts";
import { planApiPlugin } from "./plan-api.ts";
import { regenApiPlugin } from "./regen-api.ts";
import { ROUTE_SLUG } from "./route-slug.ts";
import { bridgeShimPlugin } from "./shim/vite-plugin.ts";
import { fixtureNodeModules } from "./fixture-path.ts";
import { ensureNodeModulesLink } from "./node-modules-link.ts";

export interface PreviewOptions {
  /**
   * NOTE: 0 does not mean "let the OS choose". Vite treats 0 as "no port
   * configured" and falls back to its own default, so two callers passing 0
   * collide. Callers that need a dynamic port must probe for one and pass it
   * concretely (see server/src/preview-pool.ts's findFreePort).
   */
  port?: number;
  /**
   * Vite's base path. The hosted server proxies each preview at
   * `/preview/<projectId>/`, and without a matching base every asset URL the
   * dev server generates (`/src/main.tsx`, `/@vite/client`) points at the
   * PROXY's root instead of the project's, so the page loads and every module
   * 404s. Undefined leaves Vite's own default ("/"), which is what the local
   * `npm run preview` wants.
   */
  base?: string;
}

/**
 * Vite's own default `server.fs.allow` is `searchForWorkspaceRoot(root)`,
 * which walks up looking for a workspace marker (`package-lock.json`,
 * `pnpm-workspace.yaml`, ...) and, in this monorepo, lands on the REPO ROOT
 * — meaning by default every project's dev server can serve, via Vite's
 * `/@fs/<absolute-path>` endpoint, every OTHER project's files, and every
 * other repo file (the identity database included), to anyone who can reach
 * IT AT ALL. Under the hosted server the ownership check only bounds WHICH
 * project's child answers a request — it says nothing about which files
 * that child is willing to serve once reached. Found live: authenticated as
 * the owner of exactly one project, through the real proxy, another
 * project's `overrides/*.json`, another project's `src/main.tsx`, and an
 * arbitrary repo file were all readable byte-for-byte (task 4's manual
 * verification, follow-up review).
 *
 * Narrowed to exactly the project directory, plus — if `node_modules` is a
 * symlink/junction rather than a real directory — the real location it
 * resolves to. This codebase junctions every generated project's
 * `node_modules` to one shared install (`orchestrator`'s
 * `ensure_node_modules`, used by every real generation path, not just
 * soak/testing) to avoid an `npm install` per project; that real location is
 * a genuine, load-bearing external dependency every project needs to
 * resolve modules from (confirmed empirically: a project's own
 * `node_modules/.vite/deps/react.js` request resolves through this exact
 * junction). Nothing broader is added — a real, non-symlinked
 * `node_modules` contributes nothing extra here, since it is already inside
 * `root`.
 */
export function resolveFsAllow(root: string): string[] {
  const allow = [root];
  const projectNodeModules = join(root, "node_modules");
  if (existsSync(projectNodeModules)) {
    try {
      const real = realpathSync(projectNodeModules);
      if (real !== projectNodeModules) allow.push(real);
    } catch {
      // Unreadable node_modules is not this function's problem — nothing to
      // add, and the project directory itself is still allowed.
    }
  }
  return allow;
}

/**
 * `createServer`'s inline `server.fs.allow` (set below, to `resolveFsAllow`'s
 * result) is NOT the last word on the resolved value. Vite merges the
 * project's own loaded `configFile` with this inline config via
 * `mergeConfig(fileConfig, inlineConfig)`, and `mergeConfig` CONCATENATES
 * array values rather than letting one override the other — so a project
 * `vite.config.ts` declaring its own `server.fs.allow` (e.g. `[".."]`, or
 * anything wider than the project directory) does not get replaced by the
 * narrow list below, it gets APPENDED to, reopening exactly the cross-tenant
 * `/@fs/` read the rest of this file's `fs.allow`/`deny` exists to close —
 * and the project's `vite.config.ts` is itself unowned, UNVALIDATED input
 * (scaffold copied verbatim into every project, never generated by any
 * agent, but nobody has reviewed it either — see `resolveFsAllow`'s own
 * comment on why this narrowing exists at all).
 *
 * `configResolved` runs AFTER that merge, so overwriting
 * `resolvedConfig.server.fs.allow` there — rather than relying on the inline
 * config's `fs.allow` alone — makes the narrow list authoritative regardless
 * of what the project's own config declares. Confirmed against Vite's own
 * source (`resolveServerOptions`, called before plugin `configResolved` hooks
 * run) that no later step re-derives or freezes `server.fs.allow` from the
 * merged config after this hook runs — the mutation here is what
 * `isFileLoadingAllowed` actually reads at request time.
 *
 * `normalizePath` (forward slashes, even on Windows) matters here in a way
 * it would not for the inline `fs.allow` above: Vite's OWN merge/resolution
 * step (`resolveServerOptions`, which runs the inline value through this
 * same normalization before this hook ever sees it) already produces
 * forward-slash paths for every OTHER entry `isFileLoadingAllowed` compares
 * against (the request path itself is normalized the same way). Assigning
 * `resolveFsAllow`'s raw, `node:path`-joined result here — backslash-
 * separated on Windows — bypasses that normalization and makes every
 * comparison fail, denying access to the project's OWN files, not just
 * whatever the project's config tried to widen. Caught empirically: this
 * silently 403'd `startPreviewServer`'s already-passing "still serves the
 * project's own files" case the first time this hook was added, precisely
 * because that case runs on Windows in this repo's own dev environment.
 *
 * `resolveFsAllow(root)` alone is not the full safe list, either.
 * `resolveServerOptions` (still Vite's own, still running before this hook)
 * unconditionally appends its OWN client directory — the on-disk location of
 * `/@vite/client`, the HMR runtime every dev page loads — to whatever `allow`
 * it resolves, UNLESS that directory is already covered by an existing
 * entry. A first version of this hook blindly REPLACED the merged array with
 * `resolveFsAllow(root)` alone, silently dropping that addition whenever the
 * project directory's own `node_modules` doesn't happen to contain Vite
 * itself (true of every fixture/generated project here — Vite runs from
 * THIS package's own installation, not the project's). The result compiled
 * clean and passed every `fetch`-based unit test (none of which load a real
 * page in a browser), but blanked every real preview: caught only by
 * `compiler/e2e/shim.spec.ts`, which does. `vitePackageRoot` below is
 * resolved the same way Node itself would resolve `import "vite"` from this
 * file — wherever that actually is (hoisted to a workspace root, vendored
 * locally, or anything else), not a guessed, hardcoded relative path — and
 * added to the trusted set alongside `resolveFsAllow(root)`. It carries no
 * per-tenant secret (it's this deployment's own shared tooling, the same for
 * every project, already trusted by `resolveFsAllow`'s own node_modules-
 * junction case), so widening to cover it is safe in exactly the way
 * widening to a project's `".."` is not.
 */
function enforceFsAllowPlugin(root: string): Plugin {
  const vitePackageRoot = fileURLToPath(new URL(".", import.meta.resolve("vite/package.json")));
  return {
    name: "sitewright:enforce-fs-allow",
    apply: "serve",
    configResolved(resolvedConfig) {
      resolvedConfig.server.fs.allow = [...resolveFsAllow(root), vitePackageRoot].map((p) => normalizePath(p));
    },
  };
}

export async function startPreviewServer(
  projectDir: string,
  options: PreviewOptions = {},
): Promise<ViteDevServer> {
  const root = resolve(projectDir);
  const configFile = join(root, "vite.config.ts");
  if (!existsSync(configFile)) {
    throw new Error(`No vite.config.ts found in "${root}"; cannot serve preview.`);
  }

  // X1. Before Vite loads the project's own `vite.config.ts` — which imports
  // `@tailwindcss/vite` and therefore needs the project's `node_modules` to
  // resolve. A generated project BORROWS the fixture's via a directory link
  // holding an ABSOLUTE path, so the link only works in the layout that made
  // it: a container-built project opened on the host, or any project after the
  // repository root is renamed, has a dangling link and the server dies on
  // `Failed to resolve import "@tailwindcss/vite"` — which surfaced to users as
  // 500s the editor blamed on "its generation is still running".
  //
  // HERE, rather than in `server/src/preview-pool.ts` where it was first
  // written: that import pulled compiler's source into server's stricter
  // tsconfig (`exactOptionalPropertyTypes`, `moduleResolution: node16`) and
  // broke its typecheck on pre-existing incompatibilities. server/ and
  // compiler/ are deliberately decoupled — see `max-body-bytes.ts`, whose
  // constant is duplicated rather than imported for the same reason. This spot
  // needs no cross-package dependency and covers BOTH callers: the hosted
  // pool's child and `npm run preview` locally.
  //
  // Local mode stays byte-identical: `fixtures/acme-landing` owns a REAL
  // `node_modules` directory, so this reports "kept" and touches nothing.
  const link = ensureNodeModulesLink(root, fixtureNodeModules());
  if (link.action === "repaired") {
    console.log(`preview: repaired a stale node_modules link (was ${link.staleTarget})`);
  } else if (link.action === "unavailable") {
    // Logged, never thrown: `createServer` below produces the real, actionable
    // error, and an exception from a best-effort repair would replace it.
    console.warn(`preview: could not link node_modules — ${link.reason}`);
  }

  const server = await createServer({
    root,
    configFile,
    base: options.base,
    plugins: [
      bridgeShimPlugin(),
      overridesApiPlugin(root),
      regenApiPlugin(root),
      planApiPlugin(root),
      exportApiPlugin(root),
      enforceFsAllowPlugin(root),
    ],
    // The editor runs on a different origin (port) and fetches manifest.json
    // from this server; cors must be explicit. overrides/ is written by the
    // editor while the preview is live — the preview app never consumes it,
    // so the watcher must not react (a reload would interrupt editing).
    server: {
      // Explicit, not left to Vite's own "localhost" default: on at least one
      // real Windows dev machine, Node resolves the bare hostname "localhost"
      // to the IPv6 loopback (::1) ONLY, not 127.0.0.1 — confirmed empirically
      // (task 4's manual verification, the first time a real Vite child ran
      // behind server/src/preview-pool.ts's real, non-mocked `verifyPort`).
      // That check, and preview-proxy.ts's upstream requests, both target the
      // IPv4 loopback address by a literal IP, so a child that bound only to
      // ::1 was unreachable to both — `acquire()` failed every single spawn,
      // on every retry, with no test able to see it (every unit test injects
      // a fake `verifyPort`). Binding by IP number removes the ambiguity
      // "localhost" carries across machines/OS DNS configuration.
      host: "127.0.0.1",
      port: options.port ?? 5273,
      strictPort: true,
      cors: true,
      watch: { ignored: ["**/overrides/**", "**/.regen-backup/**"] },
      fs: {
        // Set here too (not just by `enforceFsAllowPlugin`'s `configResolved`
        // hook below) so a project with no `fs.allow` of its own — the common
        // case — never even needs the backstop; see that plugin's comment for
        // why the hook, not this line alone, is what makes the value
        // authoritative against a project config that DOES declare one.
        allow: resolveFsAllow(root),
        // Vite resolves an OMITTED `deny` to its own defaults, but an
        // explicit array here is taken as-is, not merged with them — so
        // Vite's own defaults (env files, cert/key files, .npmrc, .git) are
        // repeated verbatim rather than silently dropped, alongside the two
        // new entries this fix adds. `*.db`/`*.db-{wal,shm}` are NOT in
        // Vite's own default deny list, and the documented deployment
        // (CLAUDE.md) puts the identity store — session ids, argon2 hashes —
        // at `server/data/identity.db`, inside the repo root `fs.allow` used
        // to default to. Explicit defence in depth even though the narrowed
        // `allow` above should already put every one of these out of reach:
        // per Vite's own docs, "plugins can potentially access files through
        // alternative paths or symlinks," which is exactly the class of bug
        // this whole fix responds to.
        deny: [
          ".env", ".env.*", "*.{crt,pem,key,p12,pfx,cer,der}",
          ".npmrc", ".yarnrc.yml", "**/.git/**",
          "**/*.db", "**/*.db-{wal,shm}",
        ],
      },
    },
  });
  await server.listen();
  return server;
}

/**
 * Editor persistence endpoints (PRD 6): the preview server owns the project
 * directory, so it is the natural writer for the editor's two files —
 * GET/PUT /__overrides/<route-slug>  -> overrides/<route-slug>.overrides.json
 * GET/PUT /__overrides-history       -> overrides/.editor-history.json
 * Only the editor writes overrides; agents never touch this directory.
 */
/** Exported for direct testing (preview.test.ts) — mirrors regen-api.ts's already-exported `regenApiPlugin`, driven the same way there via a fake Vite `configureServer` server. */
export function overridesApiPlugin(projectRoot: string): Plugin {
  return {
    name: "sitewright:overrides-api",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = req.url?.split("?")[0] ?? "";
        if (url === "/__overrides-history") {
          handleFileEndpoint(req, res, join(projectRoot, "overrides", ".editor-history.json"), {
            version: 1,
            snapshots: [{}],
            index: 0,
          });
          return;
        }
        const match = /^\/__overrides\/([^/]+)$/.exec(url);
        if (match !== null) {
          const slug = match[1]!;
          if (!ROUTE_SLUG.test(slug)) {
            res.statusCode = 400;
            res.end("invalid route slug");
            return;
          }
          handleFileEndpoint(req, res, join(projectRoot, "overrides", `${slug}.overrides.json`), {
            version: 1,
            route: "/",
            overrides: [],
          });
          return;
        }
        next();
      });
    },
  };
}

function handleFileEndpoint(
  req: IncomingMessage,
  res: ServerResponse,
  filePath: string,
  emptyDefault: unknown,
): void {
  if (req.method === "GET") {
    res.setHeader("Content-Type", "application/json");
    res.end(existsSync(filePath) ? readFileSync(filePath, "utf8") : JSON.stringify(emptyDefault));
    return;
  }
  if (req.method === "PUT") {
    // Bounded BEFORE accumulation, not after: `proxyHttp` (the hosted
    // server's reverse proxy) pipes a request body straight through without
    // buffering it, so this accumulation — turning the body into one
    // in-memory Buffer[] before ever calling JSON.parse — is where an
    // unbounded body actually threatens memory, in THIS process, the one
    // serving every other request for the project. See max-body-bytes.ts's
    // own comment for why the cap lives here rather than in the proxy.
    const chunks: Buffer[] = [];
    let size = 0;
    let tooLarge = false;
    req.on("data", (chunk: Buffer) => {
      if (tooLarge) return; // already answered and destroyed below
      size += chunk.length;
      if (size > MAX_BODY_BYTES) {
        tooLarge = true;
        // Stop reading rather than accumulating further — destroying the
        // request also stops it from ever emitting "end", so the guard on
        // "end" below is defence in depth, not the primary mechanism.
        req.destroy();
        res.statusCode = 413;
        res.end("request body too large");
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      if (tooLarge) return; // 413 already answered above
      try {
        const body: unknown = JSON.parse(Buffer.concat(chunks).toString("utf8"));
        mkdirSync(join(filePath, ".."), { recursive: true });
        writeFileSync(filePath, `${JSON.stringify(body, null, 2)}\n`);
        res.statusCode = 204;
        res.end();
      } catch {
        res.statusCode = 400;
        res.end("invalid JSON body");
      }
    });
    return;
  }
  res.statusCode = 405;
  res.end();
}
