// server/src/preview-pool.ts
/**
 * One Vite preview subprocess per open project, spawned, reused, reaped and
 * capped.
 *
 * Never loads a generated project in THIS process: everything that runs the
 * project's own code — its `vite.config.ts` and plugin chain (unowned
 * scaffold copied verbatim into every project, never generated by any agent),
 * its model-generated page/section source — runs in a child, spawned with a
 * deliberately narrowed environment (see `PreviewPool.buildChildEnv`, and
 * `scrubbedEnv`/`buildAgentEnv` in `agent-env.ts`, which do the actual
 * narrowing). `vite.config.ts` is UNVALIDATED, not model-generated — nobody
 * has reviewed it either way, which is the actual reason nothing in this
 * child's environment or stdout is trusted.
 *
 * Three properties this file exists to hold, all covered by
 * `preview-pool.test.ts`:
 *   - a process with work in flight (`retain`/`release`) is NEVER reaped,
 *     however long it has been running — a page regen takes about five
 *     minutes and looks, from the outside, exactly like an idle tab;
 *   - the child inherits neither the master key nor the host's own
 *     `ANTHROPIC_API_KEY` — a keyless user must get NO key, never the
 *     operator's;
 *   - a child is never `unref()`'d — an orphaned Vite server holding a port
 *     open past the parent's own lifetime is the exact failure this pool
 *     exists to bound.
 *
 * A fourth, easy to miss until a review found it: the child's `stdout` is
 * NOT a trust boundary. It runs the project's own unvalidated
 * `vite.config.ts` — nobody has reviewed it, and it can print to stdout
 * before `compiler/scripts/preview.ts` ever does. A well-formed `PREVIEW_READY`
 * line is therefore only ever a HINT that the child believes it is ready,
 * never the source of truth for the port traffic gets proxied to — see
 * `spawnAndAwaitReady` and `verifyPort`.
 *
 * A fifth (FIX 2, a whole-branch review): a warm child's key is fixed at the
 * moment it was spawned — `buildChildEnv` only ever runs again for a FRESH
 * spawn, never for a reused entry. Before this fix, `acquire()`'s reuse path
 * (below) handed back an already-running child without ever asking whether
 * the owner's key had changed since spawn — a keyless user who saves a key,
 * or ANY user who rotates one, kept talking to a child holding the OLD
 * state (no key at all, or the old key) until the next idle reap, up to 15
 * minutes away and never sooner while the project stayed in use. The first
 * of those is the dangerous direction: `orchestrator/src/orchestrator/
 * config.py`'s `load_dotenv(..., override=False)` means an ABSENT injected
 * key silently falls through to `orchestrator/.env` — the OPERATOR's own
 * key — so a keyless child spawned before a user ever saved one would go on
 * to spend the operator's money on that user's behalf, the exact "silent
 * transfer" `scrubbedEnv`'s own comment (below) says it exists to prevent.
 * `acquire()` now fingerprints (never stores, see `fingerprintOf`) the key a
 * child was ACTUALLY spawned with, compares it against the owner's CURRENT
 * key on every reuse, and — for a warm, idle entry only — kills and
 * respawns on a mismatch. See `acquire()`'s own comment for the busy-child
 * policy this cannot apply unconditionally.
 */
import { spawn } from "node:child_process";
import type { EventEmitter } from "node:events";
import { createConnection, createServer } from "node:net";
import type { DatabaseSync } from "node:sqlite";
import { fileURLToPath } from "node:url";
import {
  buildAgentEnv,
  DisabledUserError,
  MissingApiKeyError,
  resolveApiKey,
  scrubbedEnv,
  UnknownUserError,
} from "./agent-env.ts";
import { fingerprintOf, getApiKeyFingerprint } from "./api-keys.ts";
import type { Project } from "./projects.ts";
import { resolveProjectDirectory } from "./projects.ts";
import { redactSecrets } from "./redact.ts";
import { findUserById } from "./users.ts";

export const MAX_PREVIEWS = 6;

/**
 * Bounds the CONCURRENT-START multiplier on the spend cap, task 4's second
 * gap. `checkSpendCap` (require-budget.ts) only ever evaluates spend already
 * recorded in `usage_event`, and a billable request's own spend lands there
 * at ingest — after the run finishes, not before. So N billable requests
 * in flight at once for one user all evaluate the SAME pre-run total: the
 * spec accepts one run overshooting the cap, but nothing before this bounded
 * N. Small and per-user on purpose: it caps how many runs one user can have
 * simultaneously under-evaluation, not overall throughput, and one user
 * hammering this must never throttle a different one.
 */
export const MAX_BILLABLE_IN_FLIGHT_PER_USER = 2;

/** A truly idle preview (no requests, no in-flight work) this long gets reaped. */
const DEFAULT_IDLE_MS = 15 * 60 * 1000;

/**
 * A cold Vite start on a large generated project is seconds, not
 * milliseconds. This is generous on purpose: it exists only to fail loudly
 * — reject the caller's `acquire()` — rather than hang a request forever if
 * a child never announces readiness at all.
 */
const SPAWN_TIMEOUT_MS = 60_000;

/**
 * `findFreePort` + `acquire`'s retry loop below: probing a port and then
 * asking Vite to bind it is inherently a check-then-use race (something
 * else can grab the same port in between). Retrying a handful of times is
 * the mitigation.
 */
const MAX_SPAWN_ATTEMPTS = 3;

export class PreviewCapacityError extends Error {
  constructor() {
    super(`preview capacity reached: at most ${MAX_PREVIEWS} preview processes may run at once`);
    this.name = "PreviewCapacityError";
  }
}

export interface PreviewProcess {
  projectId: string;
  port: number;
  base: string;
  inFlight: number;
  lastUsedAt: number;
}

/**
 * The minimal shape the pool needs from a spawned child — deliberately NOT
 * node:child_process's `ChildProcess` itself, so a test's fake need not
 * implement the dozens of members (stdin, connected, disconnect, send, …)
 * the pool will never touch. `kill()` takes no signal: the pool always wants
 * the default (SIGTERM), so there is nothing for a caller to pass.
 */
export interface SpawnedChild {
  readonly pid?: number;
  readonly killed?: boolean;
  readonly stdout: EventEmitter;
  readonly stderr: EventEmitter;
  // Optional signal: the pool's default call is plain `kill()` (SIGTERM), but
  // `killWithEscalation` below needs to follow up with an explicit "SIGKILL"
  // when the child ignores that -- Vite installs its own
  // `process.once("SIGTERM")` that awaits `server.close()`, which can stall.
  kill(signal?: string): boolean;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- matches EventEmitter's own (loose, overloaded) signature; see spawnedChild's callers, which only ever pass a two-arg "exit" listener.
  on(event: string, listener: (...args: any[]) => void): unknown;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  off(event: string, listener: (...args: any[]) => void): unknown;
}

export type SpawnFn = (
  command: string,
  args: string[],
  options: { env: NodeJS.ProcessEnv },
) => SpawnedChild;

/**
 * Binds a `node:net` server on port 0 (the one place port 0 is safe: this
 * server is closed again before its port is ever used), reads back the
 * OS-assigned port, and resolves that number.
 *
 * Vite itself does NOT honour port 0 — it treats 0 as "no port configured"
 * and falls back to its own default (5173), so every child asking for 0
 * would collide on the same port. The parent must probe and pass a concrete
 * port instead, which is what every caller of this function does.
 */
export function findFreePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const probe = createServer();
    probe.on("error", reject);
    probe.listen(0, () => {
      const address = probe.address();
      const port = typeof address === "object" && address !== null ? address.port : null;
      probe.close((closeError) => {
        if (closeError) {
          reject(closeError);
          return;
        }
        if (port === null) {
          reject(new Error("findFreePort: could not determine the bound port"));
          return;
        }
        resolve(port);
      });
    });
  });
}

/** A few attempts a short distance apart — see `defaultVerifyPort`. */
const VERIFY_ATTEMPTS = 10;
const VERIFY_INTERVAL_MS = 150;

function connectOnce(port: number): Promise<void> {
  return new Promise((resolve, reject) => {
    const socket = createConnection({ port, host: "127.0.0.1" });
    socket.once("connect", () => {
      socket.destroy();
      resolve();
    });
    socket.once("error", (err) => {
      socket.destroy();
      reject(err);
    });
  });
}

/**
 * Confirms `port` actually accepts a TCP connection — the one thing the
 * child cannot lie about via stdout, unlike a `PREVIEW_READY` line. A few
 * attempts a short distance apart: there is a small, real window between
 * Vite deciding to print its own readiness line and the listener actually
 * accepting connections, not because the connection itself is expected to
 * be flaky.
 *
 * Overridable via `PreviewPoolDeps.verifyPort` — the tests inject a fake
 * here for the same reason they inject a fake `spawnFn`: a test's fake
 * child never opens a real socket, so proving "acquire resolves once the
 * child is ready" and "acquire rejects and kills the child when it never
 * becomes ready" needs deterministic, instant control over this decision
 * rather than a real (and, against a port nothing is listening on, always
 * failing) network wait.
 */
async function defaultVerifyPort(port: number): Promise<void> {
  let lastError: unknown;
  for (let attempt = 1; attempt <= VERIFY_ATTEMPTS; attempt += 1) {
    try {
      await connectOnce(port);
      return;
    } catch (err) {
      lastError = err;
      if (attempt < VERIFY_ATTEMPTS) {
        await new Promise((resolveDelay) => setTimeout(resolveDelay, VERIFY_INTERVAL_MS));
      }
    }
  }
  throw new Error(
    `port ${port} never accepted a connection after ${VERIFY_ATTEMPTS} attempts (last error: ${String(lastError)})`,
  );
}

// Resolved from this file's own URL, never a hardcoded absolute path — the
// pool must keep working regardless of where the repo is checked out.
const DEFAULT_PREVIEW_SCRIPT = fileURLToPath(
  new URL("../../compiler/scripts/preview.ts", import.meta.url),
);

interface Entry {
  /**
   * Resolves once the child has announced readiness. Stored in `entries`
   * BEFORE it is awaited by the caller that created it — that is the entire
   * mechanism behind "two concurrent first requests share one spawn": a
   * second `acquire()` for the same project finds this entry already
   * present and awaits the same promise instead of spawning its own child.
   */
  readyPromise: Promise<{ child: SpawnedChild; port: number; base: string }>;
  /** Undefined until `readyPromise` resolves — a still-spawning entry has no child yet. */
  child?: SpawnedChild;
  port?: number;
  base?: string;
  inFlight: number;
  lastUsedAt: number;
  /**
   * A fingerprint (never the raw key — see `fingerprintOf`) of whatever
   * `ANTHROPIC_API_KEY` this entry's child was actually spawned with, or
   * `null` for a keyless spawn. Set once, at spawn time, and never mutated
   * in place afterward — `acquire()` compares it against the owner's
   * CURRENT fingerprint on every reuse and replaces the whole entry (see
   * `installEntry`) rather than editing this field, so a stale value is
   * never silently "corrected" out from under a caller still holding a
   * reference to the old entry object.
   */
  keyFingerprint: string | null;
}

function toPreviewProcess(projectId: string, entry: Entry & { port: number; base: string }): PreviewProcess {
  return { projectId, port: entry.port, base: entry.base, inFlight: entry.inFlight, lastUsedAt: entry.lastUsedAt };
}

export interface PreviewPoolDeps {
  db: DatabaseSync;
  masterKey: Buffer;
  projectsRoot: string;
  /** Overridable for tests; production default resolves compiler/scripts/preview.ts via import.meta.url. */
  previewCommand?: { command: string; args: string[] };
  idleMs?: number;
  now?: () => number;
  spawnFn?: SpawnFn;
  /**
   * The environment `scrubbedEnv`/`buildAgentEnv` scrub FROM. Defaults to
   * `process.env`; overridable so a test can plant a fake host
   * `ANTHROPIC_API_KEY` and prove it never reaches a child, without actually
   * mutating this process's real environment.
   */
  baseEnv?: NodeJS.ProcessEnv;
  /** Overridable for tests; production default is `defaultVerifyPort` (a real TCP connect). */
  verifyPort?: (port: number) => Promise<void>;
}

const defaultSpawnFn: SpawnFn = (command, args, options) => {
  // stdio explicitly piped for stdout/stderr: that is what guarantees they
  // are non-null Readable streams (both extend EventEmitter), which is what
  // makes the cast below sound rather than merely convenient. stdin is
  // "ignore" — nothing this pool does ever writes to a preview child's stdin.
  const child = spawn(command, args, { env: options.env, stdio: ["ignore", "pipe", "pipe"] });
  return child as unknown as SpawnedChild;
};

/**
 * How long a killed child gets to exit on its own after SIGTERM before this
 * pool escalates to SIGKILL. Vite installs its own `process.once("SIGTERM")`
 * that awaits `server.close()` before exiting — a stalled close must not hold
 * a slot, and the OS process behind it, open indefinitely. Used by both
 * `reapIdle` (fire-and-forget: the pool's own bookkeeping frees the slot
 * immediately regardless — this only bounds how long the now-untracked OS
 * process can outlive that bookkeeping, which is the exact failure this
 * module exists to prevent) and `shutdown()` (awaited — shutdown's whole job
 * is confirming every child is actually gone before it returns).
 *
 * POSIX-only in spirit: Windows has no real SIGKILL, but `child.kill(
 * "SIGKILL")` there still performs a hard terminate, so sending it
 * unconditionally is harmless cross-platform, just redundant on Windows.
 */
export const KILL_GRACE_MS = 3_000;

/**
 * How long `shutdown()` waits for a STILL-SPAWNING entry (no child yet) to
 * finish spawning before giving up on awaiting it — see `killEntry`. Without
 * a bound here, Ctrl-C during a cold spawn hung the operator's terminal for
 * up to `MAX_SPAWN_ATTEMPTS * SPAWN_TIMEOUT_MS` = 180s, because `shutdown()`
 * had nothing to kill yet and could only wait for the spawn attempt itself to
 * settle. Past this bound, `shutdown()` stops waiting on this one entry;
 * whatever eventually spawns still gets a best-effort kill in the background
 * (see `killEntry`) — the process normally exits right after `shutdown()`
 * resolves anyway (`scripts/serve.ts`), so that background cleanup is
 * defence in depth, not the primary guarantee for this case.
 */
export const SHUTDOWN_SPAWN_WAIT_MS = 3_000;

/**
 * Kills `child` with SIGTERM, waiting up to `graceMs` for it to exit before
 * escalating to SIGKILL. The returned promise always settles within
 * `graceMs` (plus however long the "exit" event itself takes to propagate) —
 * never open-ended the way a plain `child.on("exit", resolve); child.kill();`
 * would be against a child whose own SIGTERM handler stalls.
 */
function killWithEscalation(child: SpawnedChild, graceMs: number = KILL_GRACE_MS): Promise<void> {
  if (child.killed === true) return Promise.resolve();
  return new Promise((resolve) => {
    let settled = false;
    const finish = (): void => {
      if (settled) return;
      settled = true;
      child.off("exit", onExit);
      clearTimeout(timer);
      resolve();
    };
    const onExit = (): void => finish();
    child.on("exit", onExit);
    const timer = setTimeout(() => {
      // SIGTERM did not finish the job within the grace period — escalate.
      // Not awaited further here: bounding THIS promise's own duration is
      // the point, and — unlike SIGTERM — a real OS process cannot ignore
      // SIGKILL.
      child.kill("SIGKILL");
      finish();
    }, graceMs);
    child.kill();
  });
}

/**
 * Resolves with `readyPromise`'s result if it settles within `timeoutMs`, or
 * `undefined` if the timeout wins or `readyPromise` rejects (a spawn that
 * failed on its own has nothing left to kill either way). Never throws —
 * `shutdown()`'s `Promise.all` must not reject just because one entry's
 * underlying spawn attempt did.
 */
function raceReadyPromise(
  readyPromise: Promise<{ child: SpawnedChild; port: number; base: string }>,
  timeoutMs: number,
): Promise<{ child: SpawnedChild; port: number; base: string } | undefined> {
  return new Promise((resolve) => {
    let settled = false;
    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      resolve(undefined);
    }, timeoutMs);
    readyPromise.then(
      (result) => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        resolve(result);
      },
      () => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        resolve(undefined);
      },
    );
  });
}

export class PreviewPool {
  private readonly db: DatabaseSync;
  private readonly masterKey: Buffer;
  private readonly projectsRoot: string;
  private readonly previewCommand: { command: string; args: string[] };
  private readonly idleMs: number;
  private readonly now: () => number;
  private readonly spawnFn: SpawnFn;
  private readonly baseEnv: NodeJS.ProcessEnv;
  private readonly verifyPort: (port: number) => Promise<void>;
  private readonly entries = new Map<string, Entry>();
  /** Per-user count of billable requests currently in flight — see `reserveBillableSlot`. */
  private readonly billableInFlight = new Map<string, number>();

  constructor(deps: PreviewPoolDeps) {
    this.db = deps.db;
    this.masterKey = deps.masterKey;
    this.projectsRoot = deps.projectsRoot;
    this.previewCommand = deps.previewCommand ?? { command: process.execPath, args: [DEFAULT_PREVIEW_SCRIPT] };
    this.idleMs = deps.idleMs ?? DEFAULT_IDLE_MS;
    this.now = deps.now ?? (() => Date.now());
    this.spawnFn = deps.spawnFn ?? defaultSpawnFn;
    this.baseEnv = deps.baseEnv ?? process.env;
    this.verifyPort = deps.verifyPort ?? defaultVerifyPort;
  }

  /**
   * Spawns a fresh preview child for `project`, or reuses one already
   * running. Increments nothing — a caller doing work across an `await`
   * boundary (a regen, say) must call `retain()` itself so the reaper cannot
   * kill the process out from under it.
   *
   * FIX 2 (a whole-branch review — see the module comment's fifth property):
   * a WARM entry (one that already has a child) is checked against the
   * owner's CURRENT key fingerprint on every reuse. A mismatch — a keyless
   * spawn whose owner has since saved a key, a rotated key, or a key that
   * was cleared — is stale. What happens to a stale entry depends on whether
   * it is busy:
   *
   *   - IDLE (`inFlight === 0`): killed and respawned with the current key,
   *     right here, before this call returns.
   *   - BUSY (`inFlight > 0`): served AS IS, stale key and all. This is a
   *     deliberate choice, not an oversight — 4c-1's invariant is that a
   *     process with work in flight is never killed, and spec decision 13
   *     forbids killing a run halfway. The alternative (refusing the
   *     request instead of killing the child) was rejected: `acquire()` is
   *     also the plain, non-billable preview path, and refusing an ordinary
   *     asset request just because a DIFFERENT concurrent regen happens to
   *     be in flight would break live preview for the whole time that regen
   *     runs. The window this leaves open is bounded and narrow: at most
   *     the duration of whatever work is already in flight, and strictly
   *     smaller than the bug this fix closes (which could persist for the
   *     full idle-reap window, up to 15 minutes, or indefinitely while the
   *     project stayed in active use). The MOMENT `inFlight` returns to
   *     zero, the next `acquire()` — for ANY endpoint, not only a billable
   *     one — re-checks and respawns.
   *
   * A still-spawning entry (no child yet) is never treated as stale here:
   * `inFlight` is guaranteed zero for it (nothing can have called `retain()`
   * before THIS very `acquire()` call — every caller retains only after its
   * own `acquire()` resolves), so killing it out from under its own spawn
   * attempt would race `spawnWithRetries` for no benefit. It becomes
   * eligible for the stale check on the very next `acquire()`, once it is
   * actually warm.
   */
  async acquire(project: Project, ownerId: string): Promise<PreviewProcess> {
    // Checked before even the reuse lookup: a preview already running for
    // this project must stop being reachable the moment its owner is
    // disabled, not only for a fresh spawn. Without this, revocation would
    // depend on nothing else holding a warm process for that project.
    this.assertOwnerUsable(ownerId);

    const existing = this.entries.get(project.id);
    if (existing !== undefined) {
      // Every read here is synchronous (no `await` before `installEntry`'s
      // own synchronous map mutation, for the branch that takes it) — see
      // `installEntry`'s comment for why that is load-bearing: it is what
      // stops a second, concurrent `acquire()` for this SAME project from
      // also deciding to respawn and leaking an untracked second child.
      const currentFingerprint = getApiKeyFingerprint(this.db, ownerId);
      const warmAndStale = existing.child !== undefined && existing.keyFingerprint !== currentFingerprint;
      if (warmAndStale && existing.inFlight === 0) {
        return this.installEntry(project, ownerId, existing.child);
      }
      // Matching key, still spawning, or busy (served as-is — see this
      // method's own comment on the busy-child policy).
      const ready = await existing.readyPromise;
      existing.lastUsedAt = this.now();
      return { projectId: project.id, port: ready.port, base: ready.base, inFlight: existing.inFlight, lastUsedAt: existing.lastUsedAt };
    }

    return this.installEntry(project, ownerId, undefined);
  }

  /**
   * The one place a map entry is created OR replaced — a brand new spawn
   * (`priorChild` undefined) and a stale-key respawn (`priorChild` the
   * WARM child being replaced) share this so there is exactly one place
   * that constructs the readyPromise chain and writes it into `entries`.
   *
   * Everything from the synchronous top of this function down to
   * `this.entries.set(...)` runs with NO `await` in between — that is what
   * makes "two concurrent callers for the same project never both decide to
   * spawn/respawn" true, exactly the same argument the pre-existing "two
   * concurrent first requests share one spawn" comment already made for the
   * fresh-spawn case: once a caller's synchronous turn reaches this far, no
   * other call can observe `entries` mid-decision, because nothing yields
   * control back to the event loop until the replacement is already in the
   * map.
   */
  private installEntry(
    project: Project,
    ownerId: string,
    priorChild: SpawnedChild | undefined,
  ): Promise<PreviewProcess> {
    const directory = resolveProjectDirectory(this.projectsRoot, project.directory);
    const base = `/preview/${project.id}/`;
    // Authorization BEFORE capacity, deliberately: `buildChildEnv` is also
    // where an unknown or disabled owner gets refused
    // (UnknownUserError/DisabledUserError). `ensureCapacity()` below can
    // reap — and kill — another tenant's idle preview to make room; running
    // it before this owner is even confirmed allowed to use the system
    // would let a bogus or disabled request evict a legitimate one on its
    // way to being refused anyway.
    const env = this.buildChildEnv(ownerId);
    // The fingerprint of whatever key THIS env actually carries (or `null`
    // for a keyless spawn) — derived from the env handed to the child, not
    // a second, separate database read, so this can never disagree with
    // what the child was actually given.
    const keyFingerprint = env.ANTHROPIC_API_KEY !== undefined ? fingerprintOf(env.ANTHROPIC_API_KEY) : null;

    // Only a BRAND NEW map entry can trip MAX_PREVIEWS — replacing an
    // existing project's entry (the stale-key respawn path, `priorChild`
    // defined) overwrites the SAME map key, so `entries.size` never changes
    // and capacity is not a question worth asking.
    if (priorChild === undefined) this.ensureCapacity();

    // `entry` is referenced by the `.then`/`.catch` closures below before it
    // is assigned. That is safe: those closures only ever run in a later
    // microtask, and `entry` is fully assigned before this synchronous
    // function body yields (at the `await` inside the `.then` chain below).
    let entry!: Entry;
    const spawnAttempt = priorChild === undefined
      ? this.spawnWithRetries(project.id, directory, base, env)
      // The stale child is killed FIRST, and only then is a replacement
      // spawned — never the reverse, which would risk two live children for
      // one project directory at once.
      : killWithEscalation(priorChild).then(() => this.spawnWithRetries(project.id, directory, base, env));
    const readyPromise = spawnAttempt
      .then((result) => {
        entry.child = result.child;
        entry.port = result.port;
        entry.base = result.base;
        entry.lastUsedAt = this.now();
        this.attachExitHandler(project.id, entry, result.child);
        return result;
      })
      .catch((err: unknown) => {
        // A spawn that never became ready must not leave a dead placeholder
        // behind for the next caller to "reuse".
        if (this.entries.get(project.id) === entry) {
          this.entries.delete(project.id);
        }
        throw err;
      });
    entry = { readyPromise, inFlight: 0, lastUsedAt: this.now(), keyFingerprint };
    // Stored BEFORE awaiting: this is what makes two concurrent first
    // requests for the same project share this one spawn rather than both
    // independently starting a second Vite server on the same directory —
    // and, for the respawn path, what stops a second concurrent caller from
    // ALSO deciding to respawn (see this method's own comment).
    this.entries.set(project.id, entry);

    return readyPromise.then((ready) => ({
      projectId: project.id, port: ready.port, base: ready.base, inFlight: entry.inFlight, lastUsedAt: entry.lastUsedAt,
    }));
  }

  /** Marks `projectId` as doing work, so `reapIdle` will not kill it mid-run. Nested: two `retain`s need two `release`s. */
  retain(projectId: string): void {
    const entry = this.entries.get(projectId);
    if (entry === undefined) return;
    entry.inFlight += 1;
  }

  /** The counterpart to `retain`. Idleness is timed from the release that brings `inFlight` back to zero, not from when the work started. */
  release(projectId: string): void {
    const entry = this.entries.get(projectId);
    if (entry === undefined) return;
    entry.inFlight = Math.max(0, entry.inFlight - 1);
    if (entry.inFlight === 0) {
      entry.lastUsedAt = this.now();
    }
  }

  /**
   * Confirms `ownerId` currently has a resolvable API key, WITHOUT spawning
   * or touching any child — a billable compiler endpoint (the only kind that
   * actually starts a model call) calls this before ever reaching
   * `acquire`/proxy, so a keyless, disabled, unknown, or
   * undecryptable-key owner gets a mapped, actionable status immediately
   * instead of a request that reaches the orchestrator and fails deep
   * inside a subprocess as a bare 500. Unlike `buildChildEnv`, this does NOT
   * catch `MissingApiKeyError`: previewing tolerates no key (buildChildEnv
   * falls back to a scrubbed env), but a billable call genuinely needs one,
   * so the caller must see this throw. The resolved plaintext itself is
   * discarded — this method exists only for the side effect of throwing,
   * never to hand back a key.
   *
   * This method ONLY ever consults the database — it never touches a
   * warm child, so on its own it says nothing about whether an
   * ALREADY-RUNNING child for this owner's project holds the SAME key it
   * just confirmed exists. (An earlier version of this comment claimed
   * otherwise — that the mapped status here stood in for "a request that
   * reaches a possibly already-warm child," which was false: a warm,
   * keyless child could still receive a request unchanged and go on to
   * spend the OPERATOR's key via the orchestrator's dotenv fallback, not
   * fail loudly at all. FIX 2, a whole-branch review, closed that gap
   * separately.) The warm case is covered by `acquire()`'s own fingerprint
   * check, not by this method: `acquire()` kills and respawns a warm, idle
   * entry whose child's key no longer matches what this method would
   * currently resolve.
   */
  assertApiKeyUsable(ownerId: string): void {
    resolveApiKey(this.db, this.masterKey, ownerId);
  }

  /**
   * Reserves one of `userId`'s `MAX_BILLABLE_IN_FLIGHT_PER_USER` billable
   * slots, returning false (reserving nothing) once they are all held. See
   * that constant's comment for why this exists. Independent of
   * `retain`/`release`, which count work in flight against a PROJECT (for
   * the reaper); this counts billable requests in flight for a USER (for the
   * spend cap's concurrent-start multiplier) — one user can hold slots
   * against several different projects at once, and this map does not care
   * which.
   */
  reserveBillableSlot(userId: string): boolean {
    const current = this.billableInFlight.get(userId) ?? 0;
    if (current >= MAX_BILLABLE_IN_FLIGHT_PER_USER) return false;
    this.billableInFlight.set(userId, current + 1);
    return true;
  }

  /**
   * The counterpart to `reserveBillableSlot`. Must run even when the
   * reserved request FAILS — a caller that only releases on success leaks
   * one slot per failure and permanently shrinks that user's allowance.
   * Safe to call with nothing reserved (a no-op), so a caller never needs to
   * track whether its own `reserveBillableSlot` call actually succeeded
   * before deciding whether to release.
   */
  releaseBillableSlot(userId: string): void {
    const current = this.billableInFlight.get(userId) ?? 0;
    if (current <= 1) {
      this.billableInFlight.delete(userId);
    } else {
      this.billableInFlight.set(userId, current - 1);
    }
  }

  /** Kills and forgets every process idle past `idleMs` with no work in flight. Returns the killed project ids. */
  reapIdle(): string[] {
    const now = this.now();
    const killed: string[] = [];
    for (const [projectId, entry] of this.entries) {
      // Work in flight is NEVER reaped, however long it has run — checked
      // first and unconditionally, before elapsed time is even considered.
      if (entry.inFlight !== 0) continue;
      // Still spawning (no child yet): not idle in any meaningful sense.
      if (entry.child === undefined || entry.port === undefined || entry.base === undefined) continue;
      if (now - entry.lastUsedAt < this.idleMs) continue;
      // SIGTERM first, escalating to SIGKILL if the child doesn't exit
      // within KILL_GRACE_MS (see that constant's comment — Vite's own
      // SIGTERM handler awaits `server.close()`, which can stall). Not
      // awaited: this loop's own bookkeeping (below) frees the slot
      // immediately regardless of how the kill turns out — the escalation
      // only bounds how long the now-untracked OS process can survive past
      // that, which is what stops the cap from silently over-committing to
      // an orphan nobody is tracking any more.
      void killWithEscalation(entry.child);
      this.entries.delete(projectId);
      killed.push(projectId);
    }
    return killed;
  }

  /** Kills every child immediately, in-flight work notwithstanding — this is shutdown, not idle reaping. */
  async shutdown(): Promise<void> {
    const snapshot = Array.from(this.entries.values());
    this.entries.clear();
    await Promise.all(snapshot.map((entry) => this.killEntry(entry)));
  }

  list(): PreviewProcess[] {
    const result: PreviewProcess[] = [];
    for (const [projectId, entry] of this.entries) {
      if (entry.port === undefined || entry.base === undefined) continue;
      result.push(toPreviewProcess(projectId, entry as Entry & { port: number; base: string }));
    }
    return result;
  }

  private async killEntry(entry: Entry): Promise<void> {
    if (entry.child !== undefined) {
      await killWithEscalation(entry.child);
      return;
    }
    // Still spawning (no child yet): give the in-flight attempt a BOUNDED
    // window to settle before deciding what to kill — see
    // SHUTDOWN_SPAWN_WAIT_MS's comment. Unbounded here is exactly what once
    // turned a Ctrl-C during a cold spawn into a hang of up to
    // MAX_SPAWN_ATTEMPTS * SPAWN_TIMEOUT_MS (180s): shutdown() had nothing to
    // kill yet, so it could only wait for the spawn attempt itself.
    const ready = await raceReadyPromise(entry.readyPromise, SHUTDOWN_SPAWN_WAIT_MS);
    if (ready === undefined) {
      // The bound expired (or the spawn failed on its own, in which case
      // this is a no-op): don't hold shutdown() open any further waiting on
      // it. If the spawn DOES eventually complete, still make a best-effort
      // attempt to kill the result — the process normally exits right after
      // shutdown() resolves anyway (scripts/serve.ts), so this is defence in
      // depth, not the primary guarantee for this one edge case.
      void entry.readyPromise.then(
        (result) => killWithEscalation(result.child),
        () => { /* it failed on its own — nothing left to kill */ },
      );
      return;
    }
    await killWithEscalation(ready.child);
  }

  private ensureCapacity(): void {
    if (this.entries.size < MAX_PREVIEWS) return;
    this.reapIdle();
    if (this.entries.size >= MAX_PREVIEWS) {
      throw new PreviewCapacityError();
    }
  }

  private attachExitHandler(projectId: string, entry: Entry, child: SpawnedChild): void {
    child.on("exit", () => {
      // Only remove OUR OWN entry: if this project has since been respawned
      // (a newer entry object sits in the map), a stale exit event from the
      // OLD child must not delete the NEW one out from under it.
      if (this.entries.get(projectId) === entry) {
        this.entries.delete(projectId);
      }
    });
    // Permanent, unlike spawnAndAwaitReady's own "error" listener (removed by
    // `cleanup()` the moment readiness settles, success or failure either
    // way): `ChildProcess` emits "error" when a LATER `kill()` cannot deliver
    // its signal — see preview-proxy.ts's module comment, which states "an
    // 'error' event with no listener attached throws synchronously and can
    // crash the whole process" as an absolute rule this file otherwise
    // follows everywhere else. Without this, a running preview child (which
    // reaches this point precisely because readiness already settled, so the
    // temporary listener is already gone) was the one place that rule was not
    // actually kept. Logged through redactSecrets for the same reason
    // spawnAndAwaitReady's own three call sites are: this fires on the same
    // untrusted child, and the error carries a message this package did not
    // construct.
    child.on("error", (err: Error) => {
      console.error(`[preview:${projectId}] child process error: ${redactSecrets(String(err?.message ?? err))}`);
    });
  }

  /**
   * Refuses an owner who cannot use the system at all. Called on BOTH the
   * fresh-spawn and the reuse path: without it, a preview already running
   * keeps serving an owner who was disabled after it started, which would
   * make revocation depend on nothing else holding a warm process. One
   * indexed read per call, against a `requireSession` that already does a
   * session lookup plus a user read on the same request.
   *
   * `buildChildEnv` (via `resolveApiKey`) performs this exact same check
   * again on the fresh-spawn path. That duplication is deliberate, not an
   * oversight to clean up: two cheap reads here are far cheaper than the one
   * place either check is skipped.
   */
  private assertOwnerUsable(ownerId: string): void {
    const user = findUserById(this.db, ownerId);
    if (user === null) throw new UnknownUserError();
    if (user.disabledAt !== null) throw new DisabledUserError();
  }

  /**
   * Resolves the child's environment exactly once. `MissingApiKeyError`
   * means only "this user has no stored key" — previewing is free, so that
   * falls back to a scrubbed environment with no `ANTHROPIC_API_KEY` at all,
   * rather than refusing to preview. `UnknownUserError`/`DisabledUserError`
   * are NOT caught here: both mean the owner cannot use the system at all,
   * which must refuse the preview outright rather than spawn a keyless
   * child for a disabled or nonexistent account.
   */
  private buildChildEnv(ownerId: string): NodeJS.ProcessEnv {
    try {
      return buildAgentEnv({ db: this.db, masterKey: this.masterKey, userId: ownerId, baseEnv: this.baseEnv });
    } catch (err) {
      if (err instanceof MissingApiKeyError) {
        return scrubbedEnv(this.baseEnv);
      }
      throw err;
    }
  }

  /**
   * The retry loop only — authorization (`buildChildEnv`) has already run in
   * `acquire`, before capacity was even consulted, so nothing in here can
   * fail for an authorization reason.
   */
  private async spawnWithRetries(
    projectId: string,
    directory: string,
    base: string,
    env: NodeJS.ProcessEnv,
  ): Promise<{ child: SpawnedChild; port: number; base: string }> {
    let lastError: unknown;
    for (let attempt = 1; attempt <= MAX_SPAWN_ATTEMPTS; attempt += 1) {
      // Probing then handing Vite a concrete port is a check-then-use race —
      // something else can bind the same port between our probe and Vite's
      // own bind. That race is tolerable ONLY because the compiler side runs
      // with `strictPort` (compiler/scripts/preview.ts): losing the race is a
      // loud, immediate child exit, never a silent rebind onto a different
      // port that would leave this pool's entry pointing at the wrong
      // process. A loud exit is exactly what this retry loop is for.
      const requestedPort = await findFreePort();
      try {
        return await this.spawnAndAwaitReady(directory, requestedPort, base, env);
      } catch (err) {
        lastError = err;
      }
    }
    throw new Error(
      `preview process for project ${projectId} failed to start after ${MAX_SPAWN_ATTEMPTS} attempts: ${String(lastError)}`,
    );
  }

  private spawnAndAwaitReady(
    directory: string,
    port: number,
    base: string,
    env: NodeJS.ProcessEnv,
  ): Promise<{ child: SpawnedChild; port: number; base: string }> {
    const { command, args: baseArgs } = this.previewCommand;
    const args = [...baseArgs, directory, "--port", String(port), "--base", base];
    const child = this.spawnFn(command, args, { env });

    return new Promise((resolve, reject) => {
      let settled = false;
      let verifyStarted = false;
      let buffer = "";
      let stderrBuffer = "";

      function cleanup(): void {
        clearTimeout(timeoutHandle);
        child.off("exit", onExit);
        child.off("error", onError);
      }

      // The one place every rejection path funnels through. A failed
      // readiness wait must never leave a live, untracked Vite server
      // holding a port open — that is the exact failure this module exists
      // to bound — so every path that can end this promise in rejection
      // kills the child first (unless it is already dead). Structural on
      // purpose: a future new failure path calls this and cannot forget to
      // kill, the way the old direct-reject-on-parse-failure path once did.
      const fail = (error: Error): void => {
        if (settled) return;
        settled = true;
        cleanup();
        if (child.killed !== true) child.kill();
        reject(error);
      };

      const succeed = (): void => {
        if (settled) return;
        settled = true;
        cleanup();
        // Always the port and base THIS pool chose — never read back from
        // the child. See the PREVIEW_READY handling below for why.
        resolve({ child, port, base });
      };

      const onExit = (code: number | null): void => {
        fail(new Error(`preview process for ${directory} exited (code ${String(code)}) before announcing readiness`));
      };

      const onError = (err: Error): void => {
        // spawn() itself failing to launch at all (ENOENT, EACCES, …)
        // surfaces as an "error" event, not "exit". Without this handler
        // `acquire` would hang for the full SPAWN_TIMEOUT_MS on every one of
        // its retries instead of failing fast.
        fail(err);
      };

      const onStdoutData = (chunk: Buffer | string): void => {
        buffer += chunk.toString();
        const lines = buffer.split("\n");
        buffer = lines.pop() ?? "";
        for (const line of lines) {
          if (line.startsWith("PREVIEW_READY ")) {
            // A HINT that the child believes it is ready — never the source
            // of truth for where to send traffic. The child runs the
            // project's own unvalidated vite.config.ts: nobody has reviewed
            // it, and it could print an early, well-formed PREVIEW_READY line
            // naming any port it likes. Believing it would hand untrusted
            // input a redirect primitive (the pool would proxy every
            // request for this project to whatever port it claims). Parsed
            // only so a malformed line is logged instead of silently
            // ignored — never to extract a port or base to act on;
            // `succeed` above always uses the port/base THIS pool chose.
            try {
              JSON.parse(line.slice("PREVIEW_READY ".length));
            } catch {
              console.log(`[preview:${port}] malformed readiness line: ${redactSecrets(line)}`);
            }
            if (!verifyStarted) {
              verifyStarted = true;
              // The line only claims readiness; this confirms it against the
              // one thing that is not the child's to lie about — whether the
              // port THIS pool chose actually accepts a connection. If it
              // never does, `verifyPort` rejects and `fail` takes over
              // (which is also what closes the early-bogus-line case:
              // untrusted code printing a line before Vite is listening no
              // longer makes the pool declare readiness).
              this.verifyPort(port).then(succeed, (err: unknown) => {
                fail(err instanceof Error ? err : new Error(String(err)));
              });
            }
          } else if (line.length > 0) {
            // The CLI's own human-readable log line, or a stray console.log
            // from the generated project's own code path — one of
            // redactSecrets' three call sites in this function (see
            // redact.ts): the moment a child's output reaches a log call,
            // "no key is ever logged" stops being true by construction and
            // starts depending on this line.
            console.log(`[preview:${port}] ${redactSecrets(line)}`);
          }
        }
      };

      const onStderrData = (chunk: Buffer | string): void => {
        // Line-buffered, same as stdout above, and for the same reason: a
        // key (or anything else KEY_PATTERN matches) can arrive split across
        // two separate pipe chunks, which is an ordinary, expected thing for
        // a stream to do — chunk boundaries carry no semantic meaning.
        // Redacting each chunk independently would let either half evade
        // KEY_PATTERN and log both halves in plaintext; a completed LINE is
        // the smallest unit `redactSecrets` can be trusted to see the whole
        // of a match within.
        stderrBuffer += chunk.toString();
        const lines = stderrBuffer.split("\n");
        stderrBuffer = lines.pop() ?? "";
        for (const line of lines) {
          if (line.length > 0) console.error(`[preview:${port}] ${redactSecrets(line)}`);
        }
      };

      const timeoutHandle = setTimeout(() => {
        fail(new Error(`preview process for ${directory} did not become ready within ${SPAWN_TIMEOUT_MS}ms`));
      }, SPAWN_TIMEOUT_MS);

      child.on("exit", onExit);
      child.on("error", onError);
      child.stdout.on("data", onStdoutData);
      child.stderr.on("data", onStderrData);
    });
  }
}
