// server/src/redact.ts
/**
 * Last line of defence for log output.
 *
 * The real rule is "never pass a key to a log call" (spec, BYOK requirement 2),
 * and every call site we construct ourselves follows it directly. This exists
 * for the messages we do NOT construct — output that passes through a log call
 * without this package having chosen its content, so there is no way to audit
 * in advance whether it carries a key.
 *
 * `preview-pool.ts`'s `spawnAndAwaitReady` is exactly that: it wires a preview
 * child's stdout and stderr into `console.log`/`console.error`. That child
 * runs the project's own code — its `vite.config.ts` and plugin chain
 * (unowned scaffold copied verbatim, never generated by any agent, but never
 * reviewed either) and its model-generated page/section source — so its
 * output is untrusted and unpredictable either way, including the
 * possibility of a key appearing on a spawned process's command line or in an
 * error message. Three call sites there depend on this function: the per-line
 * stdout logger, the stderr logger, and the malformed-readiness-line logger.
 * Every provider whose key can be injected into that child must therefore be
 * covered here — see `KEY_PATTERNS`.
 * If a future call site pipes a child or subprocess's output into a log call,
 * it needs this too — the "never logged" guarantee stopped holding by
 * construction the moment the first such call site was wired in.
 */

/**
 * One entry per provider whose key can reach a child's environment, and so a
 * child's output. BYOK task 1 added the Gemini pair: a Gemini key now travels
 * to the same preview child by the same route, so leaving it out of this list
 * would have meant the "never logged" guarantee held for one provider only.
 *
 * These are deliberately NOT `api-keys.ts`'s `API_KEY_SHAPES`. Those are
 * anchored validators for a whole string; these must match a key EMBEDDED in
 * arbitrary text, so they are unanchored and open-ended — a key that has been
 * truncated or concatenated by whatever printed it must still be caught.
 *
 * Each pattern carries a minimum run length, and `AQ.` additionally a word
 * boundary, to keep ordinary log text intact: without `\b`, "FAQ." in a
 * generated site's own build output would be redacted as if it were a
 * credential prefix, and a bare "AQ." in prose would too.
 */
const KEY_PATTERNS: ReadonlyArray<{ pattern: RegExp; replacement: string }> = [
  // Anthropic: `sk-ant-` then a run of URL-safe characters. Unchanged from the
  // original, including its lack of a length floor — the prefix alone is
  // specific enough that a false positive is not a realistic concern.
  { pattern: /sk-ant-[A-Za-z0-9_-]+/g, replacement: "sk-ant-[redacted]" },
  // Google "standard" key: `AIza` + 35 characters. The floor is well under 35
  // so a truncated key is still caught.
  { pattern: /AIza[A-Za-z0-9_-]{10,}/g, replacement: "AIza[redacted]" },
  // Google AI Studio "auth" key: `AQ.` + an unknown-length body that may itself
  // contain dots.
  //
  // THE SECOND ALTERNATIVE IS NOT DECORATION, and it is the only pattern here
  // that needs one. This is the only entry anchored on a word boundary (see the
  // `FAQ.` case in redact.test.ts), and a word boundary is exactly what an
  // ESCAPE SEQUENCE can destroy: text that reads `…\nAQ.<key>` — a key at the
  // start of a line, inside a string whose newline was escaped by whatever
  // printed it, which is precisely the shape dogfood finding G1's real artefact
  // is full of — presents `n` immediately before `AQ.`, so there is no boundary
  // and the key went UNREDACTED into a log and into `job.error`. The lookbehind
  // matches the same key when the preceding whitespace is an escape sequence
  // rather than real whitespace. `FAQ.` is untouched either way: `F` is neither
  // a boundary nor an escape.
  { pattern: /(?:\b|(?<=\\[nrt0]))AQ\.[A-Za-z0-9._-]{16,}/g, replacement: "AQ.[redacted]" },
];

export function redactSecrets(text: string): string {
  let output = text;
  for (const { pattern, replacement } of KEY_PATTERNS) {
    output = output.replace(pattern, replacement);
  }
  return output;
}
