"""Page fan-out mechanics (build prompt 5.3, pipeline 2.5): template
selection per archetype, the route table text pages read hrefs from, and
the per-page assembly step. A route's sections are generated by looping
`generate_section_flow` once per section (each an independent, resumable
Kitaru execution — reused from M3 rather than reinvented); THIS module
provides the pieces around that loop that are genuinely page-level.
"""

import json
from pathlib import Path

import kitaru
from kitaru import checkpoint, flow

from orchestrator.prompts import Template, load_template
from orchestrator.section_pipeline import (
    _run_compiler_cli,
    assemble_page_index_source,
)

_TEMPLATE_CACHE: dict[str, Template] = {}

# Archetypes with a dedicated, gate-passing-canonical-example template.
# Build prompt 5.4 grew this to six; build prompt 6.1 completes the full
# 19-named-archetype catalog (agent-pipeline-spec 4.2) plus the `custom`
# escape hatch (catalog.py's twentieth, which never gets a dedicated
# template by design — contract 4.4).
DEDICATED_TEMPLATES = {
    # marketing / landing set
    "hero",
    "feature-grid",
    "feature-spotlight",
    "social-proof",
    "pricing-tiers",
    "faq-accordion",
    "cta-band",
    "stats-band",
    "team-grid",
    "contact-form",
    # storefront set
    "product-card-grid",
    "product-detail",
    "collection-header",
    "cart-drawer",
    "category-nav",
    # saas set
    "integration-grid",
    "comparison-table",
    "changelog-list",
    "docs-toc-page",
}


def select_template(archetype: str) -> Template:
    name = archetype if archetype in DEDICATED_TEMPLATES else "generic-section"
    if name not in _TEMPLATE_CACHE:
        _TEMPLATE_CACHE[name] = load_template(name)
    return _TEMPLATE_CACHE[name]


def route_table_source(routes: list[dict]) -> str:
    return json.dumps([{"slug": r["slug"], "path": r["path"], "title": r["title"]} for r in routes])


# ---------- per-page assembly (pipeline 5.2: "page.<slug>.assembled") ----------


@checkpoint
def assemble_page(run_id: str, project_dir: str, route_slug: str, sections: list[dict]) -> dict:
    """Deterministic index.tsx assembly + a gate check SCOPED to this route
    (gate 4; build prompt 5.3). Runs once per route, after every section has
    completed or exhausted retries — but sibling routes may still be mid-
    generation at that moment, so this check must not see their transient
    state any more than a section's own check does (same reasoning as
    run_gates_step's scope_route). The true whole-project check, including
    gate 6 with the real cross-process write log, runs once at the very end
    in fanout.py after every worker has finished."""
    index_source = assemble_page_index_source(route_slug=route_slug, sections=sections)
    page_dir = Path(project_dir) / "src" / "pages" / route_slug
    page_dir.mkdir(parents=True, exist_ok=True)
    (page_dir / "index.tsx").write_text(index_source, encoding="utf-8", newline="\n")

    result = _run_compiler_cli(
        ["scripts/gates.ts", project_dir, "--json", "--scope-route", route_slug]
    )
    report = json.loads(result.stdout)
    return {"passed": report["passed"], "report": report}


@flow
def assemble_page_flow(run_id: str, project_dir: str, route_slug: str, sections: list[dict]) -> dict:
    print(f"exec_id: {kitaru.current_execution_id()}", flush=True)
    return assemble_page(run_id, project_dir, route_slug, sections)
