"""Template engine (pipeline 4.1): prompts assemble from fixed blocks in
prompts/archetypes/<name>.md via {{placeholder}} substitution — nothing is
freeform-generated by an orchestrator LLM, so every prompt is loggable,
diffable, and replayable.

The rendered prompt splits into the prompt-cache seam:
  system = [SYSTEM] + [DESIGN CONTEXT]   (identical across all sections of a
                                          run — the cacheable prefix)
  user   = [PAGE CONTEXT] + [ARCHETYPE] + [SECTION BRIEF] + [REGEN]
"""

import hashlib
import re
from dataclasses import dataclass

from orchestrator.config import ORCHESTRATOR_ROOT

PROMPTS_DIR = ORCHESTRATOR_ROOT.parent / "prompts" / "archetypes"

SYSTEM_BLOCKS = ("SYSTEM", "DESIGN CONTEXT")
USER_BLOCKS = ("PAGE CONTEXT", "ARCHETYPE", "SECTION BRIEF", "REGEN")
ALL_BLOCKS = SYSTEM_BLOCKS + USER_BLOCKS

_BLOCK_HEADER = re.compile(r"^\[(SYSTEM|DESIGN CONTEXT|PAGE CONTEXT|ARCHETYPE|SECTION BRIEF|REGEN)\]\s*$", re.MULTILINE)
_PLACEHOLDER = re.compile(r"\{\{([a-z_]+)\}\}")
_FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)


@dataclass(frozen=True)
class Template:
    name: str
    archetype: str
    version: str
    content_hash: str
    blocks: dict[str, str]


@dataclass(frozen=True)
class RenderedPrompt:
    system: str
    user: str
    template_name: str
    template_version: str
    template_hash: str
    prompt_hash: str


def _short_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]


def load_template(name: str) -> Template:
    path = PROMPTS_DIR / f"{name}.md"
    raw = path.read_text(encoding="utf-8")

    frontmatter_match = _FRONTMATTER.match(raw)
    if frontmatter_match is None:
        raise ValueError(f"Template {path} has no frontmatter (--- version/archetype ---).")
    frontmatter: dict[str, str] = {}
    for line in frontmatter_match.group(1).splitlines():
        key, _, value = line.partition(":")
        frontmatter[key.strip()] = value.strip()
    body = raw[frontmatter_match.end() :]

    headers = list(_BLOCK_HEADER.finditer(body))
    blocks: dict[str, str] = {}
    for index, header in enumerate(headers):
        end = headers[index + 1].start() if index + 1 < len(headers) else len(body)
        blocks[header.group(1)] = body[header.end() : end].strip()
    missing = [block for block in ALL_BLOCKS if block not in blocks]
    if missing:
        raise ValueError(f"Template {path} is missing blocks: {missing}")

    return Template(
        name=name,
        archetype=frontmatter.get("archetype", name),
        version=frontmatter.get("version", "0.0.0"),
        content_hash=_short_hash(raw),
        blocks=blocks,
    )


def render_template(template: Template, context: dict[str, str]) -> RenderedPrompt:
    needed: set[str] = set()
    for text in template.blocks.values():
        needed.update(_PLACEHOLDER.findall(text))

    missing = needed - context.keys()
    if missing:
        raise KeyError(f"missing placeholder values: {sorted(missing)}")
    unknown = context.keys() - needed
    if unknown:
        raise KeyError(f"unknown context keys (typo?): {sorted(unknown)}")

    def substitute(text: str) -> str:
        return _PLACEHOLDER.sub(lambda match: context[match.group(1)], text)

    rendered = {name: substitute(text) for name, text in template.blocks.items()}
    for name, text in rendered.items():
        if "{{" in text:
            raise ValueError(f"unresolved placeholder survived rendering in [{name}]")

    system = "\n\n".join(f"[{name}]\n{rendered[name]}" for name in SYSTEM_BLOCKS)
    user = "\n\n".join(f"[{name}]\n{rendered[name]}" for name in USER_BLOCKS)

    return RenderedPrompt(
        system=system,
        user=user,
        template_name=template.name,
        template_version=template.version,
        template_hash=template.content_hash,
        prompt_hash=_short_hash(f"{system}\x00{user}"),
    )
